const cadastro = (nome: string, descricao: string, sql: string) =>
  [nome, descricao, "CADASTROS", sql] as const;
const fluxo = (nome: string, descricao: string, sql: string) =>
  [nome, descricao, "FLUXO_CAIXA", sql] as const;

export const FONTES_INICIAIS = [
  [
    "oracle_fluxo_validar_objetos",
    "Valida todos os objetos utilizados pelo fluxo",
    "VALIDACAO",
    `SELECT
  O.OWNER,
  O.OBJECT_NAME,
  O.OBJECT_TYPE,
  O.STATUS
FROM ALL_OBJECTS O
WHERE O.OBJECT_NAME IN (
  'ACERCAR', 'ACERCARTDIG', 'ACERDIN', 'BAIXASDUPPAG',
  'BAIXASDUPREC', 'CARTAO', 'CARTDIG', 'DUPPAG',
  'DUPPAGACERFIN', 'DUPREC', 'FILIAL', 'FILIALCONFFIN',
  'GRUPOESTAB', 'GRUPOESTABFILIAL', 'LANFIN', 'NOTA',
  'NOTAACERFIN', 'PESSOADOC', 'PLACONAN', 'PORTADOR',
  'PORTADORSALDO', 'SITUACAO', 'VSCONSULTAS'
)
ORDER BY
  O.OBJECT_NAME,
  O.OWNER`,
  ],
  [
    "oracle_fluxo_validar_colunas",
    "Valida todas as colunas utilizadas pelo fluxo",
    "VALIDACAO",
    `SELECT
  C.OWNER,
  C.TABLE_NAME,
  C.COLUMN_NAME,
  C.DATA_TYPE,
  C.NULLABLE
FROM ALL_TAB_COLUMNS C
WHERE C.TABLE_NAME IN (
  'ACERCAR', 'ACERCARTDIG', 'ACERDIN', 'CARTAO', 'CARTDIG',
  'DUPPAG', 'DUPPAGACERFIN', 'DUPREC', 'FILIAL',
  'FILIALCONFFIN', 'GRUPOESTAB', 'GRUPOESTABFILIAL',
  'LANFIN', 'NOTA', 'NOTAACERFIN', 'PESSOADOC',
  'PLACONAN', 'PORTADOR', 'PORTADORSALDO', 'SITUACAO'
)
ORDER BY
  C.TABLE_NAME,
  C.COLUMN_ID`,
  ],
  cadastro(
    "oracle_fluxo_listar_grupos_filiais",
    "Grupos de filiais e estabelecimentos do Construshow",
    `SELECT
  G.IDGRUPOESTAB IDGRUPOFILIAL,
  G.DESCRICAO GRUPOFILIAL,
  GF.ESTAB,
  F.REDUZIDO ESTABELECIMENTO,
  F.RAZAOSOC,
  F.EMPRESA
FROM GRUPOESTAB G
INNER JOIN GRUPOESTABFILIAL GF
  ON GF.IDGRUPOESTAB = G.IDGRUPOESTAB
INNER JOIN FILIAL F
  ON F.ESTAB = GF.ESTAB
WHERE COALESCE(F.INATIVA, 'N') <> 'S'
ORDER BY
  G.DESCRICAO,
  F.ESTAB`,
  ),
  cadastro(
    "oracle_fluxo_listar_filiais",
    "Estabelecimentos ativos do Construshow",
    `SELECT
  F.ESTAB,
  F.REDUZIDO ESTABELECIMENTO,
  F.RAZAOSOC,
  F.FILIAL,
  F.EMPRESA,
  F.CNPJ
FROM FILIAL F
WHERE COALESCE(F.INATIVA, 'N') <> 'S'
ORDER BY
  F.ESTAB`,
  ),
  cadastro(
    "oracle_fluxo_listar_portadores",
    "Portadores e contas por estabelecimento",
    `SELECT
  P.ESTAB,
  P.IDPORTADOR,
  P.DESCRICAO,
  P.IDBANCO,
  P.AGENCIA,
  P.CONTA,
  P.CONCILIA
FROM PORTADOR P
WHERE P.DTINATIVO IS NULL
ORDER BY
  P.ESTAB,
  P.DESCRICAO`,
  ),
  cadastro(
    "oracle_fluxo_listar_situacoes",
    "Situações financeiras",
    `SELECT
  S.IDSITUACAO,
  S.DESCRICAO
FROM SITUACAO S
ORDER BY
  S.DESCRICAO`,
  ),
  cadastro(
    "oracle_fluxo_listar_analiticas",
    "Contas analíticas por plano",
    `SELECT
  A.PLANO,
  A.REDUZIDA IDANALITICA,
  A.DESCRICAO,
  A.REDSINT,
  A.TIPOSALDO
FROM PLACONAN A
WHERE COALESCE(A.ATIVA, 'S') = 'S'
ORDER BY
  A.PLANO,
  A.DESCRICAO`,
  ),
  cadastro(
    "oracle_fluxo_listar_pessoas",
    "Pessoas para filtro e detalhamento",
    `SELECT
  P.IDPESS,
  P.NOME,
  P.FANTASIA,
  P.CNPJF
FROM PESSOADOC P
WHERE UPPER(P.NOME) LIKE UPPER(:P_BUSCA)
ORDER BY
  P.NOME
FETCH FIRST 100 ROWS ONLY`,
  ),
  fluxo(
    "oracle_fluxo_saldo_portador",
    "Saldo financeiro ou conciliado antes do período",
    `SELECT
  P.ESTAB,
  P.IDPORTADOR,
  P.DESCRICAO PORTADOR,
  ROUND(
    COALESCE(P.SDOINICIAL, 0) + SUM(
      CASE
        WHEN :P_TIPO_SALDO = 'CONCILIADO' THEN
          COALESCE(S.ENTCONCILIADA, 0) - COALESCE(S.SAICONCILIADA, 0)
        ELSE COALESCE(S.ENTRADAS, 0) - COALESCE(S.SAIDAS, 0)
      END
    ),
    2
  ) SALDO
FROM PORTADOR P
INNER JOIN PORTADORSALDO S
  ON S.ESTAB = P.ESTAB
 AND S.IDPORTADOR = P.IDPORTADOR
WHERE S.DATA < TRUNC(:P_DTINI)
  AND (:P_ESTAB IS NULL OR P.ESTAB = :P_ESTAB)
  AND (:P_IDPORTADOR IS NULL OR P.IDPORTADOR = :P_IDPORTADOR)
GROUP BY
  P.ESTAB,
  P.IDPORTADOR,
  P.DESCRICAO,
  P.SDOINICIAL`,
  ),
  fluxo(
    "oracle_fluxo_movimentos_detalhe",
    "Contas a receber e a pagar previstas, vencidas e a vencer",
    `SELECT
  D.ESTAB,
  TRUNC(D.DTVENCTO) DATA_FLUXO,
  'ENTRADA' TIPO_MOVIMENTO,
  'CONTAS_A_RECEBER' GRUPO_MOVIMENTO,
  'DUPREC' ORIGEM_MOVIMENTO,
  TO_CHAR(D.IDDUPREC) ID_DOCUMENTO_ORACLE,
  TO_CHAR(D.DUPREC) DOCUMENTO,
  D.DTEMISSAO DATA_EMISSAO,
  D.DTVENCTO DATA_VENCIMENTO,
  D.VALOR VALOR_ORIGINAL,
  D.IDPORTADOR ID_PORTADOR_ORACLE,
  P.DESCRICAO PORTADOR,
  D.IDPESS ID_PESSOA_ORACLE,
  PE.NOME PESSOA,
  D.IDSITUACAO ID_SITUACAO_ORACLE,
  SI.DESCRICAO SITUACAO,
  D.IDANALITICA ID_ANALITICA_ORACLE,
  A.DESCRICAO ANALITICA,
  COALESCE(BX.SALDO, 0) VALOR_ENTRADA,
  0 VALOR_SAIDA,
  D.HISTORICO
FROM DUPREC D
INNER JOIN TABLE(BAIXASDUPREC(D.ESTAB, D.IDDUPREC, NULL)) BX
  ON 0 = 0
LEFT JOIN PORTADOR P
  ON P.ESTAB = D.ESTAB
 AND P.IDPORTADOR = D.IDPORTADOR
LEFT JOIN PESSOADOC PE
  ON PE.IDPESS = D.IDPESS
LEFT JOIN SITUACAO SI
  ON SI.IDSITUACAO = D.IDSITUACAO
LEFT JOIN FILIALCONFFIN FC
  ON FC.ESTAB = D.ESTAB
LEFT JOIN PLACONAN A
  ON A.PLANO = FC.PLANO
 AND A.REDUZIDA = D.IDANALITICA
WHERE COALESCE(D.QUITADA, 'N') <> 'S'
  AND COALESCE(BX.SALDO, 0) <> 0
  AND D.DTVENCTO < TRUNC(:P_DTFIM) + 1
  AND (:P_ESTAB IS NULL OR D.ESTAB = :P_ESTAB)
  AND (:P_IDPORTADOR IS NULL OR D.IDPORTADOR = :P_IDPORTADOR)
  AND (:P_IDPESS IS NULL OR D.IDPESS = :P_IDPESS)
  AND (:P_IDSITUACAO IS NULL OR D.IDSITUACAO = :P_IDSITUACAO)
  AND (:P_IDANALITICA IS NULL OR D.IDANALITICA = :P_IDANALITICA)
  AND (:P_ORIGEM IS NULL OR :P_ORIGEM = 'DUPREC')
UNION ALL
SELECT
  D.ESTAB,
  TRUNC(D.DTVENCTO),
  'SAIDA',
  'CONTAS_A_PAGAR',
  'DUPPAG',
  TO_CHAR(D.IDDUPPAG),
  TO_CHAR(D.DUPPAG),
  D.DTEMISSAO,
  D.DTVENCTO,
  D.VALOR,
  D.IDPORTADOR,
  P.DESCRICAO,
  D.IDPESS,
  PE.NOME,
  D.IDSITUACAO,
  SI.DESCRICAO,
  D.IDANALITICA,
  A.DESCRICAO,
  0,
  COALESCE(BX.SALDO, 0),
  D.HISTORICO
FROM DUPPAG D
INNER JOIN TABLE(BAIXASDUPPAG(D.ESTAB, D.IDDUPPAG, NULL)) BX
  ON 0 = 0
LEFT JOIN PORTADOR P
  ON P.ESTAB = D.ESTAB
 AND P.IDPORTADOR = D.IDPORTADOR
LEFT JOIN PESSOADOC PE
  ON PE.IDPESS = D.IDPESS
LEFT JOIN SITUACAO SI
  ON SI.IDSITUACAO = D.IDSITUACAO
LEFT JOIN FILIALCONFFIN FC
  ON FC.ESTAB = D.ESTAB
LEFT JOIN PLACONAN A
  ON A.PLANO = FC.PLANO
 AND A.REDUZIDA = D.IDANALITICA
WHERE COALESCE(D.QUITADA, 'N') <> 'S'
  AND COALESCE(BX.SALDO, 0) <> 0
  AND D.DTVENCTO < TRUNC(:P_DTFIM) + 1
  AND (:P_ESTAB IS NULL OR D.ESTAB = :P_ESTAB)
  AND (:P_IDPORTADOR IS NULL OR D.IDPORTADOR = :P_IDPORTADOR)
  AND (:P_IDPESS IS NULL OR D.IDPESS = :P_IDPESS)
  AND (:P_IDSITUACAO IS NULL OR D.IDSITUACAO = :P_IDSITUACAO)
  AND (:P_IDANALITICA IS NULL OR D.IDANALITICA = :P_IDANALITICA)
  AND (:P_ORIGEM IS NULL OR :P_ORIGEM = 'DUPPAG')`,
  ),
  fluxo(
    "oracle_fluxo_recebimentos_realizados",
    "Recebimentos realizados por dinheiro, cartão de débito e PIX",
    `SELECT
  X.ESTAB,
  X.DATA_RECEBIMENTO,
  X.TIPO_FINALIZADOR,
  SUM(X.VALOR) VALOR
FROM (
  SELECT
    N.ESTAB,
    TRUNC(L.DTLANCTO) DATA_RECEBIMENTO,
    'DINHEIRO' TIPO_FINALIZADOR,
    L.VALOR
  FROM NOTA N
  INNER JOIN NOTAACERFIN NA
    ON NA.ESTAB = N.ESTAB
   AND NA.IDNOTA = N.IDNOTA
  INNER JOIN ACERDIN AD
    ON AD.ESTAB = NA.ESTAB
   AND AD.IDACERFIN = NA.IDACERFIN
  INNER JOIN LANFIN L
    ON L.ESTAB = AD.ESTAB
   AND L.IDLANFIN = AD.IDLANFIN
  WHERE N.OPERACAO = 'S'
    AND L.DTLANCTO >= TRUNC(:P_DTINI)
    AND L.DTLANCTO < TRUNC(:P_DTFIM) + 1
    AND (:P_ESTAB IS NULL OR N.ESTAB = :P_ESTAB)
  UNION ALL
  SELECT
    N.ESTAB,
    TRUNC(AC.DTEMISSAO),
    'CARTAO_DEBITO',
    AC.VALOR
  FROM NOTA N
  INNER JOIN NOTAACERFIN NA
    ON NA.ESTAB = N.ESTAB
   AND NA.IDNOTA = N.IDNOTA
  INNER JOIN ACERCAR AC
    ON AC.ESTAB = NA.ESTAB
   AND AC.IDACERFIN = NA.IDACERFIN
  INNER JOIN CARTAO C
    ON C.IDCARTAO = AC.IDCARTAO
  WHERE N.OPERACAO = 'S'
    AND C.CREDITODEBITO = 'D'
    AND AC.DTEMISSAO >= TRUNC(:P_DTINI)
    AND AC.DTEMISSAO < TRUNC(:P_DTFIM) + 1
    AND (:P_ESTAB IS NULL OR N.ESTAB = :P_ESTAB)
  UNION ALL
  SELECT
    N.ESTAB,
    TRUNC(AC.DATAHORATRANSACAO),
    'PIX',
    L.VALOR
  FROM NOTA N
  INNER JOIN NOTAACERFIN NA
    ON NA.ESTAB = N.ESTAB
   AND NA.IDNOTA = N.IDNOTA
  INNER JOIN ACERCARTDIG AC
    ON AC.ESTAB = NA.ESTAB
   AND AC.IDACERFIN = NA.IDACERFIN
  INNER JOIN CARTDIG CD
    ON CD.IDCARTDIG = AC.IDCARTDIG
  INNER JOIN LANFIN L
    ON L.ESTAB = AC.ESTAB
   AND L.IDLANFIN = AC.IDLANFIN
  WHERE N.OPERACAO = 'S'
    AND AC.TRANSACAOPIXOK = 'S'
    AND AC.DATAHORATRANSACAO >= TRUNC(:P_DTINI)
    AND AC.DATAHORATRANSACAO < TRUNC(:P_DTFIM) + 1
    AND (:P_ESTAB IS NULL OR N.ESTAB = :P_ESTAB)
) X
GROUP BY
  X.ESTAB,
  X.DATA_RECEBIMENTO,
  X.TIPO_FINALIZADOR
ORDER BY
  X.DATA_RECEBIMENTO,
  X.ESTAB`,
  ),
  fluxo(
    "oracle_fluxo_pagamentos_realizados",
    "Pagamentos efetivamente realizados por duplicata",
    `SELECT
  D.ESTAB,
  TRUNC(DA.DTPGTO) DATA_PAGAMENTO,
  D.IDDUPPAG ID_DOCUMENTO_ORACLE,
  D.IDPESS ID_PESSOA_ORACLE,
  D.IDANALITICA ID_ANALITICA_ORACLE,
  SUM(COALESCE(DA.VALOR, 0)) VALOR
FROM DUPPAG D
INNER JOIN DUPPAGACERFIN DA
  ON DA.ESTAB = D.ESTAB
 AND DA.IDDUPPAG = D.IDDUPPAG
WHERE DA.DTPGTO >= TRUNC(:P_DTINI)
  AND DA.DTPGTO < TRUNC(:P_DTFIM) + 1
  AND (:P_ESTAB IS NULL OR D.ESTAB = :P_ESTAB)
  AND (:P_IDPESS IS NULL OR D.IDPESS = :P_IDPESS)
  AND (:P_IDANALITICA IS NULL OR D.IDANALITICA = :P_IDANALITICA)
GROUP BY
  D.ESTAB,
  TRUNC(DA.DTPGTO),
  D.IDDUPPAG,
  D.IDPESS,
  D.IDANALITICA
ORDER BY
  DATA_PAGAMENTO,
  D.ESTAB`,
  ),
  [
    "oracle_fluxo_previsao_recebimentos_historico",
    "Histórico realizado dos últimos três meses para previsão inteligente",
    "PREVISAO",
    `SELECT
  X.ESTAB,
  X.DATA_RECEBIMENTO,
  X.TIPO_FINALIZADOR,
  SUM(X.VALOR) VALOR
FROM (
  SELECT
    N.ESTAB,
    TRUNC(L.DTLANCTO) DATA_RECEBIMENTO,
    'DINHEIRO' TIPO_FINALIZADOR,
    L.VALOR
  FROM NOTA N
  INNER JOIN NOTAACERFIN NA
    ON NA.ESTAB = N.ESTAB
   AND NA.IDNOTA = N.IDNOTA
  INNER JOIN ACERDIN AD
    ON AD.ESTAB = NA.ESTAB
   AND AD.IDACERFIN = NA.IDACERFIN
  INNER JOIN LANFIN L
    ON L.ESTAB = AD.ESTAB
   AND L.IDLANFIN = AD.IDLANFIN
  WHERE N.OPERACAO = 'S'
    AND L.DTLANCTO >= ADD_MONTHS(TRUNC(:P_DTINI), -3)
    AND L.DTLANCTO < TRUNC(:P_DTINI)
    AND (:P_ESTAB IS NULL OR N.ESTAB = :P_ESTAB)
  UNION ALL
  SELECT
    N.ESTAB,
    TRUNC(AC.DTEMISSAO),
    'CARTAO_DEBITO',
    AC.VALOR
  FROM NOTA N
  INNER JOIN NOTAACERFIN NA
    ON NA.ESTAB = N.ESTAB
   AND NA.IDNOTA = N.IDNOTA
  INNER JOIN ACERCAR AC
    ON AC.ESTAB = NA.ESTAB
   AND AC.IDACERFIN = NA.IDACERFIN
  INNER JOIN CARTAO C
    ON C.IDCARTAO = AC.IDCARTAO
  WHERE N.OPERACAO = 'S'
    AND C.CREDITODEBITO = 'D'
    AND AC.DTEMISSAO >= ADD_MONTHS(TRUNC(:P_DTINI), -3)
    AND AC.DTEMISSAO < TRUNC(:P_DTINI)
    AND (:P_ESTAB IS NULL OR N.ESTAB = :P_ESTAB)
  UNION ALL
  SELECT
    N.ESTAB,
    TRUNC(AC.DATAHORATRANSACAO),
    'PIX',
    L.VALOR
  FROM NOTA N
  INNER JOIN NOTAACERFIN NA
    ON NA.ESTAB = N.ESTAB
   AND NA.IDNOTA = N.IDNOTA
  INNER JOIN ACERCARTDIG AC
    ON AC.ESTAB = NA.ESTAB
   AND AC.IDACERFIN = NA.IDACERFIN
  INNER JOIN CARTDIG CD
    ON CD.IDCARTDIG = AC.IDCARTDIG
  INNER JOIN LANFIN L
    ON L.ESTAB = AC.ESTAB
   AND L.IDLANFIN = AC.IDLANFIN
  WHERE N.OPERACAO = 'S'
    AND AC.TRANSACAOPIXOK = 'S'
    AND AC.DATAHORATRANSACAO >= ADD_MONTHS(TRUNC(:P_DTINI), -3)
    AND AC.DATAHORATRANSACAO < TRUNC(:P_DTINI)
    AND (:P_ESTAB IS NULL OR N.ESTAB = :P_ESTAB)
) X
GROUP BY
  X.ESTAB,
  X.DATA_RECEBIMENTO,
  X.TIPO_FINALIZADOR`,
  ],
  fluxo(
    "oracle_fluxo_documento_detalhe",
    "Detalhe integral de um documento financeiro",
    `SELECT
  'DUPREC' ORIGEM,
  D.ESTAB,
  TO_CHAR(D.IDDUPREC) ID_DOCUMENTO,
  TO_CHAR(D.DUPREC) DOCUMENTO,
  D.DTEMISSAO,
  D.DTVENCTO,
  D.IDPESS,
  D.IDPORTADOR,
  D.IDSITUACAO,
  D.IDANALITICA,
  D.VALOR,
  D.JUROSPEND,
  D.DESCPEND,
  D.HISTORICO
FROM DUPREC D
WHERE :P_ORIGEM = 'DUPREC'
  AND TO_CHAR(D.IDDUPREC) = :P_ID_DOCUMENTO
UNION ALL
SELECT
  'DUPPAG',
  D.ESTAB,
  TO_CHAR(D.IDDUPPAG),
  TO_CHAR(D.DUPPAG),
  D.DTEMISSAO,
  D.DTVENCTO,
  D.IDPESS,
  D.IDPORTADOR,
  D.IDSITUACAO,
  D.IDANALITICA,
  D.VALOR,
  D.JUROSPEND,
  D.DESCPEND,
  D.HISTORICO
FROM DUPPAG D
WHERE :P_ORIGEM = 'DUPPAG'
  AND TO_CHAR(D.IDDUPPAG) = :P_ID_DOCUMENTO`,
  ),
  [
    "oracle_fluxo_listar_consultas_nativas",
    "Consultas nativas de fluxo existentes no Construshow",
    "VALIDACAO",
    `SELECT
  C.MODULO,
  C.DESCRICAO,
  C.SQL
FROM VSCONSULTAS C
WHERE UPPER(C.MODULO) LIKE '%FLUXOCAIXA%'
   OR UPPER(C.DESCRICAO) LIKE '%FLUXO DE CAIXA%'
ORDER BY
  C.MODULO`,
  ],
] as const;
