export const FONTES_INICIAIS = [
  [
    "oracle_fluxo_validar_objetos",
    "Valida objetos Oracle",
    "VALIDACAO",
    `/* Valida exclusivamente objetos usados pelo fluxo. */\nSELECT owner, object_name, object_type, status FROM all_objects WHERE object_name IN ('PORTADOR','PORTADORSALDO','DUPREC','DUPPAG','CHEQREC','CHEQEMI','NOTA','NOTAACERFIN','ACERDIN','ACERCAR','CARTAO','ACERCARTDIG','CARTDIG','LANFIN','FILIAL','EMPRESA','FILIALCONFFIN','PLACONAN','SITUACAO','V_SIMPLEPESS','V_FLUXOCAIXA') ORDER BY object_name`,
  ],
  [
    "oracle_fluxo_validar_colunas",
    "Valida colunas Oracle",
    "VALIDACAO",
    `/* Confirma as colunas antes da publicação de uma fonte operacional. */\nSELECT owner, table_name, column_name, data_type FROM all_tab_columns WHERE table_name IN ('PORTADOR','PORTADORSALDO','DUPREC','DUPPAG','CHEQREC','CHEQEMI','NOTA','NOTAACERFIN','ACERDIN','ACERCAR','CARTAO','ACERCARTDIG','CARTDIG','LANFIN') ORDER BY table_name, column_id`,
  ],
  [
    "oracle_fluxo_saldo_portador",
    "Saldo por portador",
    "FLUXO_CAIXA",
    `/* Fonte confirmada em V_FLUXOCAIXA e SEL_RECALC_FLUXOCAIXA.\n   :P_TIPO_SALDO = CONCILIADO usa ENTCONCILIADA/SAICONCILIADA; FINANCEIRO usa ENTRADAS/SAIDAS. */\nSELECT P.ESTAB, P.IDPORTADOR, P.DESCRICAO PORTADOR, ROUND(COALESCE(P.SDOINICIAL,0) + SUM(CASE WHEN :P_TIPO_SALDO = 'CONCILIADO' THEN COALESCE(S.ENTCONCILIADA,0)-COALESCE(S.SAICONCILIADA,0) ELSE COALESCE(S.ENTRADAS,0)-COALESCE(S.SAIDAS,0) END),2) SALDO FROM PORTADOR P JOIN PORTADORSALDO S ON S.ESTAB=P.ESTAB AND S.IDPORTADOR=P.IDPORTADOR WHERE S.DATA < :P_DTINI AND (:P_ESTAB IS NULL OR P.ESTAB=:P_ESTAB) AND (:P_IDPORTADOR IS NULL OR P.IDPORTADOR=:P_IDPORTADOR) GROUP BY P.ESTAB,P.IDPORTADOR,P.DESCRICAO,P.SDOINICIAL`,
  ],
  [
    "oracle_fluxo_movimentos_detalhe",
    "Movimentos previstos detalhados",
    "FLUXO_CAIXA",
    `/* Origens e campos confirmados na função FLUXOCAIXA e na view V_FLUXOCAIXA. */\nSELECT D.ESTAB, TRUNC(D.DTVENCTO) DATA_FLUXO, 'ENTRADA' TIPO_MOVIMENTO, 'CONTAS_A_RECEBER' GRUPO_MOVIMENTO, 'DUPREC' ORIGEM_MOVIMENTO, TO_CHAR(D.IDDUPREC) ID_DOCUMENTO_ORACLE, TO_CHAR(D.DUPREC) DOCUMENTO, D.DTEMISSAO DATA_EMISSAO, D.DTVENCTO DATA_VENCIMENTO, D.IDPORTADOR ID_PORTADOR_ORACLE, D.IDPESS ID_PESSOA_ORACLE, D.IDSITUACAO ID_SITUACAO_ORACLE, D.IDANALITICA ID_ANALITICA_ORACLE, COALESCE(D.VALOR,0)+COALESCE(D.JUROSPEND,0)-COALESCE(D.DESCPEND,0)-BX.VALREC VALOR_ENTRADA, 0 VALOR_SAIDA, D.HISTORICO FROM DUPREC D JOIN TABLE(BAIXASDUPREC(D.ESTAB,D.IDDUPREC,NULL)) BX ON 0=0 WHERE COALESCE(D.QUITADA,'N')<>'S' AND D.DTVENCTO < TRUNC(:P_DTFIM)+1 AND (:P_ESTAB IS NULL OR D.ESTAB=:P_ESTAB) UNION ALL SELECT D.ESTAB,TRUNC(D.DTVENCTO),'SAIDA','CONTAS_A_PAGAR','DUPPAG',TO_CHAR(D.IDDUPPAG),TO_CHAR(D.DUPPAG),D.DTEMISSAO,D.DTVENCTO,D.IDPORTADOR,D.IDPESS,D.IDSITUACAO,D.IDANALITICA,0,COALESCE(D.VALOR,0)+COALESCE(D.JUROSPEND,0)-COALESCE(D.DESCPEND,0)-BX.VALREC,D.HISTORICO FROM DUPPAG D JOIN TABLE(BAIXASDUPPAG(D.ESTAB,D.IDDUPPAG,NULL)) BX ON 0=0 WHERE COALESCE(D.QUITADA,'N')<>'S' AND D.DTVENCTO < TRUNC(:P_DTFIM)+1 AND (:P_ESTAB IS NULL OR D.ESTAB=:P_ESTAB)`,
  ],
  [
    "oracle_fluxo_recebimentos_realizados",
    "Recebimentos realizados por dinheiro, cartão de débito e PIX",
    "FLUXO_CAIXA",
    `/* Relações confirmadas no dicionário Viasoft.
   DINHEIRO: NOTA -> NOTAACERFIN -> ACERDIN -> LANFIN.
   CARTAO_DEBITO: NOTA -> NOTAACERFIN -> ACERCAR -> CARTAO.
   PIX: NOTA -> NOTAACERFIN -> ACERCARTDIG -> CARTDIG -> LANFIN.
   Não utiliza tabelas sem metadados confirmados. */
SELECT X.ESTAB, X.DATA_FLUXO, X.TIPO_FINALIZADOR, SUM(X.VALOR) VALOR
FROM (
  SELECT N.ESTAB, TRUNC(L.DTLANCTO) DATA_FLUXO, 'DINHEIRO' TIPO_FINALIZADOR, L.VALOR
  FROM NOTA N
  JOIN NOTAACERFIN NA ON NA.ESTAB=N.ESTAB AND NA.IDNOTA=N.IDNOTA
  JOIN ACERDIN AD ON AD.ESTAB=NA.ESTAB AND AD.IDACERFIN=NA.IDACERFIN
  JOIN LANFIN L ON L.ESTAB=AD.ESTAB AND L.IDLANFIN=AD.IDLANFIN
  WHERE N.OPERACAO='S'
    AND L.DTLANCTO>=TRUNC(:P_DTINI) AND L.DTLANCTO<TRUNC(:P_DTFIM)+1
    AND (:P_ESTAB IS NULL OR N.ESTAB=:P_ESTAB)
  UNION ALL
  SELECT N.ESTAB, TRUNC(AC.DTEMISSAO), 'CARTAO_DEBITO', AC.VALOR
  FROM NOTA N
  JOIN NOTAACERFIN NA ON NA.ESTAB=N.ESTAB AND NA.IDNOTA=N.IDNOTA
  JOIN ACERCAR AC ON AC.ESTAB=NA.ESTAB AND AC.IDACERFIN=NA.IDACERFIN
  JOIN CARTAO C ON C.IDCARTAO=AC.IDCARTAO
  WHERE N.OPERACAO='S' AND C.CREDITODEBITO='D'
    AND AC.DTEMISSAO>=TRUNC(:P_DTINI) AND AC.DTEMISSAO<TRUNC(:P_DTFIM)+1
    AND (:P_ESTAB IS NULL OR N.ESTAB=:P_ESTAB)
  UNION ALL
  SELECT N.ESTAB, TRUNC(AC.DATAHORATRANSACAO), 'PIX', L.VALOR
  FROM NOTA N
  JOIN NOTAACERFIN NA ON NA.ESTAB=N.ESTAB AND NA.IDNOTA=N.IDNOTA
  JOIN ACERCARTDIG AC ON AC.ESTAB=NA.ESTAB AND AC.IDACERFIN=NA.IDACERFIN
  JOIN CARTDIG CD ON CD.IDCARTDIG=AC.IDCARTDIG
  JOIN LANFIN L ON L.ESTAB=AC.ESTAB AND L.IDLANFIN=AC.IDLANFIN
  WHERE N.OPERACAO='S' AND AC.TRANSACAOPIXOK='S'
    AND AC.DATAHORATRANSACAO>=TRUNC(:P_DTINI) AND AC.DATAHORATRANSACAO<TRUNC(:P_DTFIM)+1
    AND (:P_ESTAB IS NULL OR N.ESTAB=:P_ESTAB)
) X
GROUP BY X.ESTAB, X.DATA_FLUXO, X.TIPO_FINALIZADOR
ORDER BY X.DATA_FLUXO, X.ESTAB, X.TIPO_FINALIZADOR`,
  ],
  [
    "oracle_fluxo_previsao_recebimentos_historico",
    "Histórico real para previsão inteligente",
    "PREVISAO",
    `/* Fontes prontas confirmadas nos metadados e consultas Viasoft.\n   DINHEIRO: NOTA -> NOTAACERFIN -> ACERDIN -> LANFIN.\n   CARTAO_DEBITO: NOTA -> NOTAACERFIN -> ACERCAR -> CARTAO.\n   PIX: NOTA -> NOTAACERFIN -> ACERCARTDIG -> CARTDIG -> LANFIN; somente transações pagas.\n   PREVFINFLUXOCAIXA e MOVFINECF não são usados nesta fonte. */\nSELECT X.ESTAB, X.DATA_RECEBIMENTO, X.TIPO_FINALIZADOR, SUM(X.VALOR) VALOR FROM ( SELECT N.ESTAB, TRUNC(L.DTLANCTO) DATA_RECEBIMENTO, 'DINHEIRO' TIPO_FINALIZADOR, L.VALOR FROM NOTA N JOIN NOTAACERFIN NA ON NA.ESTAB=N.ESTAB AND NA.IDNOTA=N.IDNOTA JOIN ACERDIN AD ON AD.ESTAB=NA.ESTAB AND AD.IDACERFIN=NA.IDACERFIN JOIN LANFIN L ON L.ESTAB=AD.ESTAB AND L.IDLANFIN=AD.IDLANFIN WHERE N.OPERACAO='S' AND L.DTLANCTO>=ADD_MONTHS(TRUNC(:P_DTINI),-3) AND L.DTLANCTO<TRUNC(:P_DTINI) AND (:P_ESTAB IS NULL OR N.ESTAB=:P_ESTAB) UNION ALL SELECT N.ESTAB, TRUNC(AC.DTEMISSAO), 'CARTAO_DEBITO', AC.VALOR FROM NOTA N JOIN NOTAACERFIN NA ON NA.ESTAB=N.ESTAB AND NA.IDNOTA=N.IDNOTA JOIN ACERCAR AC ON AC.ESTAB=NA.ESTAB AND AC.IDACERFIN=NA.IDACERFIN JOIN CARTAO C ON C.IDCARTAO=AC.IDCARTAO WHERE N.OPERACAO='S' AND (C.CREDITODEBITO='D' OR C.TIPO='D') AND AC.DTEMISSAO>=ADD_MONTHS(TRUNC(:P_DTINI),-3) AND AC.DTEMISSAO<TRUNC(:P_DTINI) AND (:P_ESTAB IS NULL OR N.ESTAB=:P_ESTAB) UNION ALL SELECT N.ESTAB, TRUNC(L.DTLANCTO), 'PIX', L.VALOR FROM NOTA N JOIN NOTAACERFIN NA ON NA.ESTAB=N.ESTAB AND NA.IDNOTA=N.IDNOTA JOIN ACERCARTDIG AP ON AP.ESTAB=NA.ESTAB AND AP.IDACERFIN=NA.IDACERFIN JOIN CARTDIG CD ON CD.IDCARTDIG=AP.IDCARTDIG JOIN LANFIN L ON L.ESTAB=AP.ESTAB AND L.IDLANFIN=AP.IDLANFIN WHERE N.OPERACAO='S' AND AP.TRANSACAOPIXOK='S' AND L.DTLANCTO>=ADD_MONTHS(TRUNC(:P_DTINI),-3) AND L.DTLANCTO<TRUNC(:P_DTINI) AND (:P_ESTAB IS NULL OR N.ESTAB=:P_ESTAB) ) X GROUP BY X.ESTAB,X.DATA_RECEBIMENTO,X.TIPO_FINALIZADOR`,
  ],
  [
    "oracle_fluxo_listar_filiais",
    "Lista filiais",
    "CADASTROS",
    `/* FILIAL e EMPRESA confirmadas nos metadados. */ SELECT F.ESTAB, F.RAZAOSOC, F.EMPRESA FROM FILIAL F ORDER BY F.ESTAB`,
  ],
  [
    "oracle_fluxo_listar_portadores",
    "Lista portadores",
    "CADASTROS",
    `/* PORTADOR confirmado nos metadados. */ SELECT ESTAB, IDPORTADOR, DESCRICAO FROM PORTADOR ORDER BY ESTAB, DESCRICAO`,
  ],
  [
    "oracle_fluxo_listar_situacoes",
    "Lista situações",
    "CADASTROS",
    `/* SITUACAO confirmada nos metadados. */ SELECT IDSITUACAO, DESCRICAO FROM SITUACAO ORDER BY DESCRICAO`,
  ],
  [
    "oracle_fluxo_listar_analiticas",
    "Lista analíticas",
    "CADASTROS",
    `/* PLACONAN confirmada nos metadados. */ SELECT PLANO, REDUZIDA IDANALITICA, DESCRICAO FROM PLACONAN ORDER BY DESCRICAO`,
  ],
  [
    "oracle_fluxo_listar_pessoas",
    "Lista pessoas",
    "CADASTROS",
    `/* V_SIMPLEPESS confirmada nos metadados. */ SELECT IDPESS, NOME FROM V_SIMPLEPESS WHERE UPPER(NOME) LIKE UPPER(:P_BUSCA) ORDER BY NOME FETCH FIRST 100 ROWS ONLY`,
  ],
  [
    "oracle_fluxo_listar_consultas_nativas",
    "Consultas nativas de fluxo",
    "VALIDACAO",
    `/* VSCONSULTAS é o catálogo funcional do Construshow. */ SELECT MODULO, DESCRICAO, SQL FROM VSCONSULTAS WHERE UPPER(MODULO) LIKE '%FLUXOCAIXA%' OR UPPER(DESCRICAO) LIKE '%FLUXO DE CAIXA%' ORDER BY MODULO`,
  ],
  [
    "oracle_fluxo_documento_detalhe",
    "Detalhe completo do documento financeiro",
    "FLUXO_CAIXA",
    `/* Campos de DUPREC e DUPPAG confirmados nos metadados. */ SELECT 'DUPREC' ORIGEM,D.ESTAB,TO_CHAR(D.IDDUPREC) ID_DOCUMENTO,TO_CHAR(D.DUPREC) DOCUMENTO,D.DTEMISSAO,D.DTVENCTO,D.IDPESS,D.IDPORTADOR,D.IDSITUACAO,D.IDANALITICA,D.VALOR,D.JUROSPEND,D.DESCPEND,D.HISTORICO FROM DUPREC D WHERE :P_ORIGEM='DUPREC' AND TO_CHAR(D.IDDUPREC)=:P_ID_DOCUMENTO UNION ALL SELECT 'DUPPAG',D.ESTAB,TO_CHAR(D.IDDUPPAG),TO_CHAR(D.DUPPAG),D.DTEMISSAO,D.DTVENCTO,D.IDPESS,D.IDPORTADOR,D.IDSITUACAO,D.IDANALITICA,D.VALOR,D.JUROSPEND,D.DESCPEND,D.HISTORICO FROM DUPPAG D WHERE :P_ORIGEM='DUPPAG' AND TO_CHAR(D.IDDUPPAG)=:P_ID_DOCUMENTO`,
  ],
] as const;
